Repository LionnoiL/petmarket, pull requests merged in 2024-01, with the labels that each got.

#50 Зображення юзера
  src/main/java/org/petmarket/advertisements/advertisement/dto/AuthorResponseDto.java
  src/main/java/org/petmarket/advertisements/advertisement/dto/AuthorShortResponseDto.java
  src/main/java/org/petmarket/advertisements/images/service/AdvertisementImageService.java
  src/main/java/org/petmarket/aws/s3/S3Service.java
  src/main/java/org/petmarket/images/ImageConverter.java
  src/main/java/org/petmarket/images/ImageResizer.java
  src/main/java/org/petmarket/images/ImageService.java
  src/main/java/org/petmarket/images/WebpConverter.java
  src/main/java/org/petmarket/users/controller/UserController.java
  src/main/java/org/petmarket/users/dto/UserResponseDto.java
  src/main/java/org/petmarket/users/entity/User.java
  src/main/java/org/petmarket/users/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V2023.12.29.001__user_image.sql
Labels: enhancement

#51 Рефакторинг ексепшенів
  src/main/java/org/petmarket/advertisements/advertisement/controller/AdvertisementController.java
  src/main/java/org/petmarket/errorhandling/ErrorResponse.java
  src/main/java/org/petmarket/errorhandling/GlobalExceptionHandler.java
  src/main/java/org/petmarket/security/jwt/AccessDeniedHandlerJwt.java
  src/main/java/org/petmarket/security/jwt/AuthenticationEntryPointJwt.java
Labels: bug, enhancement

#52 Додано поле reviewsCount в User
  src/main/java/org/petmarket/advertisements/advertisement/dto/AuthorResponseDto.java
  src/main/java/org/petmarket/users/dto/UserResponseDto.java
  src/main/java/org/petmarket/users/entity/User.java
  src/main/resources/db/migration/V2024.01.03.001__user_add_review_count.sql
Labels: enhancement

#53 added cleanup of old drafts images
  src/main/java/org/petmarket/advertisements/images/repository/AdvertisementImageRepository.java
  src/main/java/org/petmarket/advertisements/images/scheduler/AdvertisementImageScheduler.java
  src/main/java/org/petmarket/advertisements/images/service/AdvertisementImageService.java
  src/main/java/org/petmarket/config/SchedulingConfig.java
  src/main/resources/application.properties
Labels: enhancement

#54 Перевірка знаходження міста в методі getByIds
  src/main/java/org/petmarket/location/service/CityService.java
Labels: bug

#61 Filter information
  src/main/java/org/petmarket/advertisements/advertisement/controller/AdvertisementController.java
  src/main/java/org/petmarket/advertisements/advertisement/dto/AdvertisementPriceRangeDto.java
  src/main/java/org/petmarket/advertisements/advertisement/repository/AdvertisementRepository.java
  src/main/java/org/petmarket/advertisements/advertisement/service/AdvertisementService.java
  src/main/java/org/petmarket/advertisements/attributes/controller/AttributeController.java
Labels: enhancement

#64 Ендпоінт отримання данних для побудови фільтру
  src/main/java/org/petmarket/advertisements/advertisement/mapper/AdvertisementResponseTranslateMapper.java
  src/main/java/org/petmarket/advertisements/attributes/dto/AttributeGroupResponseDto.java
  src/main/java/org/petmarket/advertisements/attributes/dto/AttributeGroupShortResponseDto.java
  src/main/java/org/petmarket/advertisements/attributes/dto/AttributeResponseDto.java
  src/main/java/org/petmarket/advertisements/attributes/dto/AttributeShortResponseDto.java
  src/main/java/org/petmarket/advertisements/attributes/entity/AttributeGroup.java
  src/main/java/org/petmarket/advertisements/attributes/mapper/AttributeShortMapper.java
  src/main/java/org/petmarket/advertisements/attributes/repository/AttributeRepository.java
  src/main/java/org/petmarket/advertisements/attributes/service/AttributeService.java
  src/main/java/org/petmarket/advertisements/filter/controller/FilterController.java
  src/main/java/org/petmarket/advertisements/filter/dto/FilterDto.java
  src/main/java/org/petmarket/advertisements/filter/service/FilterService.java
  src/main/java/org/petmarket/breeds/dto/BreedShortResponseDto.java
  src/main/java/org/petmarket/breeds/mapper/BreedMapper.java
  src/main/java/org/petmarket/breeds/service/impl/BreedServiceImpl.java
Labels: enhancement

#65 Виправлений фільтр
  src/main/java/org/petmarket/advertisements/advertisement/repository/AdvertisementRepository.java
  src/main/java/org/petmarket/advertisements/filter/dto/FilterDto.java
  src/main/java/org/petmarket/advertisements/filter/service/FilterService.java
  src/main/java/org/petmarket/breeds/dto/BreedFilterDto.java
  src/main/java/org/petmarket/breeds/dto/BreedShortResponseDto.java
  src/main/java/org/petmarket/breeds/mapper/BreedMapper.java
  src/main/java/org/petmarket/breeds/service/BreedService.java
  src/main/java/org/petmarket/breeds/service/impl/BreedServiceImpl.java
  src/main/java/org/petmarket/location/service/CityService.java
Labels: enhancement

#67 Виправлення багу додавання оголошення
  src/main/java/org/petmarket/advertisements/advertisement/service/AdvertisementService.java
  src/main/java/org/petmarket/advertisements/category/entity/AdvertisementCategory.java
Labels: bug

#69 Blog attributes
  src/main/java/org/petmarket/advertisements/attributes/dto/AttributeResponseDto.java
  src/main/java/org/petmarket/blog/controller/BlogAttributeController.java
  src/main/java/org/petmarket/blog/controller/BlogPostController.java
  src/main/java/org/petmarket/blog/controller/admin/BlogAttributeAdminController.java
  src/main/java/org/petmarket/blog/dto/attribute/BlogPostAttributeRequestDto.java
  src/main/java/org/petmarket/blog/dto/attribute/BlogPostAttributeResponseDto.java
  src/main/java/org/petmarket/blog/dto/attribute/BlogPostAttributeTranslateDto.java
  src/main/java/org/petmarket/blog/dto/posts/BlogPostRequestDto.java
  src/main/java/org/petmarket/blog/dto/posts/BlogPostResponseDto.java
  src/main/java/org/petmarket/blog/entity/BlogAttribute.java
  src/main/java/org/petmarket/blog/entity/BlogAttributeTranslation.java
  src/main/java/org/petmarket/blog/entity/Post.java
  src/main/java/org/petmarket/blog/mapper/BlogAttributeMapper.java
  src/main/java/org/petmarket/blog/mapper/BlogPostMapper.java
  src/main/java/org/petmarket/blog/repository/BlogAttributeRepository.java
  src/main/java/org/petmarket/blog/repository/PostRepository.java
  src/main/java/org/petmarket/blog/service/AttributeService.java
  src/main/java/org/petmarket/blog/service/CategoryService.java
  src/main/java/org/petmarket/blog/service/PostService.java
  src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
  src/main/java/org/petmarket/blog/service/impl/CategoryServiceImpl.java
  src/main/java/org/petmarket/blog/service/impl/PostServiceImpl.java
  src/main/resources/db/migration/V2024.01.27.001__add_blog_attributes.sql
  src/main/resources/db/migration/V2024.01.27.002__add_blog_attributes_data.sql
  src/test/java/org/petmarket/blog/service/impl/AttributeServiceImplTest.java
Labels: enhancement
